--
-- PostgreSQL database dump
--

\restrict zuYwE4w22bKg9EfYKY5fAJ9P4QualjF1bLPvZnooZChXhKiigPNHnNS5cC774Sd

-- Dumped from database version 15.17 (Debian 15.17-1.pgdg13+1)
-- Dumped by pg_dump version 15.17 (Debian 15.17-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agent_profiles; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.agent_profiles (
    id bigint NOT NULL,
    address character varying(255),
    availability_time character varying(255),
    avatar character varying(255),
    bio text,
    contact_name character varying(255),
    date_of_birth date,
    email character varying(255),
    online_status character varying(255),
    phone_number character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT agent_profiles_online_status_check CHECK (((online_status)::text = ANY ((ARRAY['ONLINE'::character varying, 'AWAY'::character varying, 'OFFLINE'::character varying])::text[])))
);


ALTER TABLE public.agent_profiles OWNER TO linkedu_user;

--
-- Name: agent_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.agent_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agent_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    message text,
    seen boolean NOT NULL,
    "timestamp" timestamp(6) without time zone,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.chat_messages OWNER TO linkedu_user;

--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cover_letter_documents; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.cover_letter_documents (
    content text,
    target_program character varying(255),
    target_university character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.cover_letter_documents OWNER TO linkedu_user;

--
-- Name: cv_documents; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.cv_documents (
    certificates character varying(255),
    email character varying(255),
    experience character varying(255),
    projects character varying(255),
    skills character varying(255),
    soft_skills character varying(255),
    summary character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.cv_documents OWNER TO linkedu_user;

--
-- Name: destinations; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.destinations (
    id bigint NOT NULL,
    country_name character varying(255) NOT NULL,
    description text,
    offers character varying(1000),
    paragraph text,
    universities character varying(1000)
);


ALTER TABLE public.destinations OWNER TO linkedu_user;

--
-- Name: destinations_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.destinations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.destinations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diploma_documents; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.diploma_documents (
    degree character varying(255),
    field_of_study character varying(255),
    graduation_year character varying(255),
    institution character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.diploma_documents OWNER TO linkedu_user;

--
-- Name: documents; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    document_type character varying(255) NOT NULL,
    file_name character varying(255),
    file_path character varying(255),
    status character varying(255),
    uploaded_at timestamp(6) without time zone,
    student_id bigint NOT NULL,
    verified_by bigint,
    CONSTRAINT documents_document_type_check CHECK (((document_type)::text = ANY ((ARRAY['CV'::character varying, 'PASSPORT'::character varying, 'ID_CARD'::character varying, 'DIPLOMA'::character varying, 'TRANSCRIPT'::character varying, 'COVER_LETTER'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT documents_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.documents OWNER TO linkedu_user;

--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verification_tokens; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.email_verification_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    verified_at timestamp(6) without time zone
);


ALTER TABLE public.email_verification_tokens OWNER TO linkedu_user;

--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.email_verification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feedback; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.feedback (
    id bigint NOT NULL,
    comment text,
    created_at timestamp(6) without time zone,
    rating integer NOT NULL,
    agent_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.feedback OWNER TO linkedu_user;

--
-- Name: feedback_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guest_profiles; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.guest_profiles (
    id bigint NOT NULL,
    address character varying(255),
    availability_time character varying(255),
    avatar character varying(255),
    bio text,
    date_of_birth date,
    online_status character varying(255),
    phone_number character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT guest_profiles_online_status_check CHECK (((online_status)::text = ANY ((ARRAY['ONLINE'::character varying, 'AWAY'::character varying, 'OFFLINE'::character varying])::text[])))
);


ALTER TABLE public.guest_profiles OWNER TO linkedu_user;

--
-- Name: guest_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.guest_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guest_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: id_card_documents; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.id_card_documents (
    birthday character varying(255),
    num_id character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.id_card_documents OWNER TO linkedu_user;

--
-- Name: options; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.options (
    id bigint NOT NULL,
    correct boolean NOT NULL,
    option_text character varying(255) NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.options OWNER TO linkedu_user;

--
-- Name: options_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: other_documents; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.other_documents (
    document_title character varying(255),
    notes text,
    id bigint NOT NULL
);


ALTER TABLE public.other_documents OWNER TO linkedu_user;

--
-- Name: passport_documents; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.passport_documents (
    expiry_date character varying(255),
    issue_date character varying(255),
    issuing_country character varying(255),
    last_name character varying(255),
    name character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.passport_documents OWNER TO linkedu_user;

--
-- Name: product_keys; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.product_keys (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    key_value character varying(255) NOT NULL,
    used boolean NOT NULL
);


ALTER TABLE public.product_keys OWNER TO linkedu_user;

--
-- Name: product_keys_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.product_keys ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_keys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: progress; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.progress (
    id bigint NOT NULL,
    stage character varying(255),
    status character varying(255),
    updated_at timestamp(6) without time zone,
    student_id bigint NOT NULL,
    updated_by bigint,
    CONSTRAINT progress_stage_check CHECK (((stage)::text = ANY ((ARRAY['ORIENTATION'::character varying, 'DOSSIER_PREPARATION'::character varying, 'DOCUMENT_COLLECTION'::character varying, 'LANGUAGE_TESTS'::character varying, 'UNIVERSITY_SELECTION'::character varying, 'APPLICATION_SUBMISSION'::character varying, 'INTERVIEW_PREPARATION'::character varying, 'ACCEPTANCE_LETTER'::character varying, 'VISA_APPLICATION'::character varying, 'ACCOMMODATION'::character varying, 'TRAVEL_PLANNING'::character varying, 'PRE_DEPARTURE'::character varying, 'ARRIVAL_SETTLEMENT'::character varying])::text[]))),
    CONSTRAINT progress_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.progress OWNER TO linkedu_user;

--
-- Name: progress_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: question_quiz_assignments; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.question_quiz_assignments (
    id bigint NOT NULL,
    assigned_by bigint,
    question_id bigint,
    quiz_id bigint
);


ALTER TABLE public.question_quiz_assignments OWNER TO linkedu_user;

--
-- Name: question_quiz_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.question_quiz_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_quiz_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    correct_option character varying(255),
    optiona character varying(255),
    optionb character varying(255),
    optionc character varying(255),
    optiond character varying(255),
    question_text text NOT NULL,
    question_type character varying(255),
    created_by bigint,
    quiz_id bigint,
    CONSTRAINT questions_question_type_check CHECK (((question_type)::text = ANY ((ARRAY['MCQ'::character varying, 'TEXT'::character varying])::text[])))
);


ALTER TABLE public.questions OWNER TO linkedu_user;

--
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_attempts; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.quiz_attempts (
    id bigint NOT NULL,
    completed_at timestamp(6) without time zone,
    passed boolean,
    score double precision,
    quiz_id bigint NOT NULL,
    reviewed_by bigint,
    student_id bigint NOT NULL
);


ALTER TABLE public.quiz_attempts OWNER TO linkedu_user;

--
-- Name: quiz_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.quiz_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quizzes; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.quizzes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255),
    end_time timestamp(6) without time zone,
    language character varying(255),
    start_time timestamp(6) without time zone,
    title character varying(255) NOT NULL,
    created_by bigint NOT NULL
);


ALTER TABLE public.quizzes OWNER TO linkedu_user;

--
-- Name: quizzes_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.quizzes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizzes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_answers; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.student_answers (
    id bigint NOT NULL,
    selected_option character varying(255),
    status character varying(255),
    submitted_at timestamp(6) without time zone,
    question_id bigint,
    quiz_attempt_id bigint,
    student_id bigint,
    CONSTRAINT student_answers_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CORRECT'::character varying, 'INCORRECT'::character varying])::text[])))
);


ALTER TABLE public.student_answers OWNER TO linkedu_user;

--
-- Name: student_answers_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.student_answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_profiles; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.student_profiles (
    id bigint NOT NULL,
    address character varying(255),
    availability_time character varying(255),
    avatar character varying(255),
    bio text,
    budget double precision,
    college_type character varying(255),
    current_study_level character varying(255),
    date_of_birth date,
    languages jsonb,
    online_status character varying(255),
    phone_number character varying(255),
    speciality character varying(255),
    university_year integer,
    wished_study_level character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT student_profiles_college_type_check CHECK (((college_type)::text = ANY ((ARRAY['PRIVATE'::character varying, 'PUBLIC'::character varying])::text[]))),
    CONSTRAINT student_profiles_current_study_level_check CHECK (((current_study_level)::text = ANY ((ARRAY['HIGH_SCHOOL'::character varying, 'BACHELOR'::character varying, 'MASTER'::character varying, 'PHD'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT student_profiles_online_status_check CHECK (((online_status)::text = ANY ((ARRAY['ONLINE'::character varying, 'AWAY'::character varying, 'OFFLINE'::character varying])::text[]))),
    CONSTRAINT student_profiles_wished_study_level_check CHECK (((wished_study_level)::text = ANY ((ARRAY['HIGH_SCHOOL'::character varying, 'BACHELOR'::character varying, 'MASTER'::character varying, 'PHD'::character varying, 'OTHER'::character varying])::text[])))
);


ALTER TABLE public.student_profiles OWNER TO linkedu_user;

--
-- Name: student_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.student_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_quiz_assignments; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.student_quiz_assignments (
    id bigint NOT NULL,
    assigned_at timestamp(6) without time zone,
    completed boolean,
    assigned_by bigint,
    quiz_id bigint NOT NULL,
    student_id bigint NOT NULL
);


ALTER TABLE public.student_quiz_assignments OWNER TO linkedu_user;

--
-- Name: student_quiz_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.student_quiz_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_quiz_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.test (
    id bigint NOT NULL
);


ALTER TABLE public.test OWNER TO linkedu_user;

--
-- Name: ticket_responses; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.ticket_responses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    response_text text,
    agent_id bigint,
    ticket_id bigint
);


ALTER TABLE public.ticket_responses OWNER TO linkedu_user;

--
-- Name: ticket_responses_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.ticket_responses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_responses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tickets; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.tickets (
    id bigint NOT NULL,
    availability_date_time timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    description text,
    google_meet_link character varying(500),
    object character varying(255) NOT NULL,
    rejection_reason character varying(500),
    status character varying(255),
    updated_at timestamp(6) without time zone,
    agent_id bigint,
    student_id bigint,
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.tickets OWNER TO linkedu_user;

--
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transcript_documents; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.transcript_documents (
    academic_year character varying(255),
    average character varying(255),
    institution character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.transcript_documents OWNER TO linkedu_user;

--
-- Name: users; Type: TABLE; Schema: public; Owner: linkedu_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    address character varying(255),
    birth_date date,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    email_verified boolean NOT NULL,
    enabled boolean NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    role character varying(30) NOT NULL,
    username character varying(255) NOT NULL,
    assigned_agent_id bigint,
    product_key_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['STUDENT'::character varying, 'AGENT'::character varying, 'ADMIN'::character varying, 'LANGUAGE_TEACHER'::character varying, 'GUEST'::character varying, 'USER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO linkedu_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: linkedu_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: agent_profiles; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.agent_profiles (id, address, availability_time, avatar, bio, contact_name, date_of_birth, email, online_status, phone_number, user_id) FROM stdin;
\.


--
-- Data for Name: chat_messages; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.chat_messages (id, message, seen, "timestamp", receiver_id, sender_id) FROM stdin;
\.


--
-- Data for Name: cover_letter_documents; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.cover_letter_documents (content, target_program, target_university, id) FROM stdin;
\.


--
-- Data for Name: cv_documents; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.cv_documents (certificates, email, experience, projects, skills, soft_skills, summary, id) FROM stdin;
\.


--
-- Data for Name: destinations; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.destinations (id, country_name, description, offers, paragraph, universities) FROM stdin;
\.


--
-- Data for Name: diploma_documents; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.diploma_documents (degree, field_of_study, graduation_year, institution, id) FROM stdin;
\.


--
-- Data for Name: documents; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.documents (id, document_type, file_name, file_path, status, uploaded_at, student_id, verified_by) FROM stdin;
\.


--
-- Data for Name: email_verification_tokens; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.email_verification_tokens (id, expiry_date, token, user_id, verified_at) FROM stdin;
\.


--
-- Data for Name: feedback; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.feedback (id, comment, created_at, rating, agent_id, student_id) FROM stdin;
\.


--
-- Data for Name: guest_profiles; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.guest_profiles (id, address, availability_time, avatar, bio, date_of_birth, online_status, phone_number, user_id) FROM stdin;
\.


--
-- Data for Name: id_card_documents; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.id_card_documents (birthday, num_id, id) FROM stdin;
\.


--
-- Data for Name: options; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.options (id, correct, option_text, question_id) FROM stdin;
\.


--
-- Data for Name: other_documents; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.other_documents (document_title, notes, id) FROM stdin;
\.


--
-- Data for Name: passport_documents; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.passport_documents (expiry_date, issue_date, issuing_country, last_name, name, id) FROM stdin;
\.


--
-- Data for Name: product_keys; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.product_keys (id, created_at, key_value, used) FROM stdin;
\.


--
-- Data for Name: progress; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.progress (id, stage, status, updated_at, student_id, updated_by) FROM stdin;
\.


--
-- Data for Name: question_quiz_assignments; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.question_quiz_assignments (id, assigned_by, question_id, quiz_id) FROM stdin;
\.


--
-- Data for Name: questions; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.questions (id, correct_option, optiona, optionb, optionc, optiond, question_text, question_type, created_by, quiz_id) FROM stdin;
\.


--
-- Data for Name: quiz_attempts; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.quiz_attempts (id, completed_at, passed, score, quiz_id, reviewed_by, student_id) FROM stdin;
\.


--
-- Data for Name: quizzes; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.quizzes (id, created_at, description, end_time, language, start_time, title, created_by) FROM stdin;
\.


--
-- Data for Name: student_answers; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.student_answers (id, selected_option, status, submitted_at, question_id, quiz_attempt_id, student_id) FROM stdin;
\.


--
-- Data for Name: student_profiles; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.student_profiles (id, address, availability_time, avatar, bio, budget, college_type, current_study_level, date_of_birth, languages, online_status, phone_number, speciality, university_year, wished_study_level, user_id) FROM stdin;
\.


--
-- Data for Name: student_quiz_assignments; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.student_quiz_assignments (id, assigned_at, completed, assigned_by, quiz_id, student_id) FROM stdin;
\.


--
-- Data for Name: test; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.test (id) FROM stdin;
\.


--
-- Data for Name: ticket_responses; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.ticket_responses (id, created_at, response_text, agent_id, ticket_id) FROM stdin;
\.


--
-- Data for Name: tickets; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.tickets (id, availability_date_time, created_at, description, google_meet_link, object, rejection_reason, status, updated_at, agent_id, student_id) FROM stdin;
\.


--
-- Data for Name: transcript_documents; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.transcript_documents (academic_year, average, institution, id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: linkedu_user
--

COPY public.users (id, address, birth_date, created_at, email, email_verified, enabled, first_name, last_name, password, phone_number, role, username, assigned_agent_id, product_key_id) FROM stdin;
\.


--
-- Name: agent_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.agent_profiles_id_seq', 1, false);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.chat_messages_id_seq', 1, false);


--
-- Name: destinations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.destinations_id_seq', 1, false);


--
-- Name: documents_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.documents_id_seq', 1, false);


--
-- Name: email_verification_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.email_verification_tokens_id_seq', 1, false);


--
-- Name: feedback_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.feedback_id_seq', 1, false);


--
-- Name: guest_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.guest_profiles_id_seq', 1, false);


--
-- Name: options_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.options_id_seq', 1, false);


--
-- Name: product_keys_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.product_keys_id_seq', 1, false);


--
-- Name: progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.progress_id_seq', 1, false);


--
-- Name: question_quiz_assignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.question_quiz_assignments_id_seq', 1, false);


--
-- Name: questions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.questions_id_seq', 1, false);


--
-- Name: quiz_attempts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.quiz_attempts_id_seq', 1, false);


--
-- Name: quizzes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.quizzes_id_seq', 1, false);


--
-- Name: student_answers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.student_answers_id_seq', 1, false);


--
-- Name: student_profiles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.student_profiles_id_seq', 1, false);


--
-- Name: student_quiz_assignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.student_quiz_assignments_id_seq', 1, false);


--
-- Name: ticket_responses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.ticket_responses_id_seq', 1, false);


--
-- Name: tickets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.tickets_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: linkedu_user
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: agent_profiles agent_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.agent_profiles
    ADD CONSTRAINT agent_profiles_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: cover_letter_documents cover_letter_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.cover_letter_documents
    ADD CONSTRAINT cover_letter_documents_pkey PRIMARY KEY (id);


--
-- Name: cv_documents cv_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.cv_documents
    ADD CONSTRAINT cv_documents_pkey PRIMARY KEY (id);


--
-- Name: destinations destinations_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.destinations
    ADD CONSTRAINT destinations_pkey PRIMARY KEY (id);


--
-- Name: diploma_documents diploma_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.diploma_documents
    ADD CONSTRAINT diploma_documents_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: email_verification_tokens email_verification_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.email_verification_tokens
    ADD CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id);


--
-- Name: feedback feedback_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_pkey PRIMARY KEY (id);


--
-- Name: guest_profiles guest_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.guest_profiles
    ADD CONSTRAINT guest_profiles_pkey PRIMARY KEY (id);


--
-- Name: id_card_documents id_card_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.id_card_documents
    ADD CONSTRAINT id_card_documents_pkey PRIMARY KEY (id);


--
-- Name: options options_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.options
    ADD CONSTRAINT options_pkey PRIMARY KEY (id);


--
-- Name: other_documents other_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.other_documents
    ADD CONSTRAINT other_documents_pkey PRIMARY KEY (id);


--
-- Name: passport_documents passport_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.passport_documents
    ADD CONSTRAINT passport_documents_pkey PRIMARY KEY (id);


--
-- Name: product_keys product_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.product_keys
    ADD CONSTRAINT product_keys_pkey PRIMARY KEY (id);


--
-- Name: progress progress_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.progress
    ADD CONSTRAINT progress_pkey PRIMARY KEY (id);


--
-- Name: question_quiz_assignments question_quiz_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.question_quiz_assignments
    ADD CONSTRAINT question_quiz_assignments_pkey PRIMARY KEY (id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: quiz_attempts quiz_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id);


--
-- Name: quizzes quizzes_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT quizzes_pkey PRIMARY KEY (id);


--
-- Name: student_answers student_answers_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_answers
    ADD CONSTRAINT student_answers_pkey PRIMARY KEY (id);


--
-- Name: student_profiles student_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT student_profiles_pkey PRIMARY KEY (id);


--
-- Name: student_quiz_assignments student_quiz_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_quiz_assignments
    ADD CONSTRAINT student_quiz_assignments_pkey PRIMARY KEY (id);


--
-- Name: test test_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.test
    ADD CONSTRAINT test_pkey PRIMARY KEY (id);


--
-- Name: ticket_responses ticket_responses_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.ticket_responses
    ADD CONSTRAINT ticket_responses_pkey PRIMARY KEY (id);


--
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- Name: transcript_documents transcript_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.transcript_documents
    ADD CONSTRAINT transcript_documents_pkey PRIMARY KEY (id);


--
-- Name: users uk5lg0gwu9i0e338b3hsrbqfb87; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk5lg0gwu9i0e338b3hsrbqfb87 UNIQUE (product_key_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: guest_profiles uk71u2kjkb5uuf2g47vwuhse2m3; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.guest_profiles
    ADD CONSTRAINT uk71u2kjkb5uuf2g47vwuhse2m3 UNIQUE (user_id);


--
-- Name: student_profiles ukhlcwb2egnj8mj3e0mouse1lgy; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT ukhlcwb2egnj8mj3e0mouse1lgy UNIQUE (user_id);


--
-- Name: product_keys ukjbfmknwqfa0cjmn7ityohook4; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.product_keys
    ADD CONSTRAINT ukjbfmknwqfa0cjmn7ityohook4 UNIQUE (key_value);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: agent_profiles ukryi1mro1uwvyr3aotwximyphp; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.agent_profiles
    ADD CONSTRAINT ukryi1mro1uwvyr3aotwximyphp UNIQUE (user_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: question_quiz_assignments fk1f4qyt05mir2er0c2660cnb93; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.question_quiz_assignments
    ADD CONSTRAINT fk1f4qyt05mir2er0c2660cnb93 FOREIGN KEY (assigned_by) REFERENCES public.users(id);


--
-- Name: transcript_documents fk1qg2yy0tq8hrybr3ia4gjbrab; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.transcript_documents
    ADD CONSTRAINT fk1qg2yy0tq8hrybr3ia4gjbrab FOREIGN KEY (id) REFERENCES public.documents(id);


--
-- Name: quizzes fk1qg4klxor82vbamctkjechwe2; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.quizzes
    ADD CONSTRAINT fk1qg4klxor82vbamctkjechwe2 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: student_quiz_assignments fk22pgnigi0cq6oie8v6ahi6npn; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_quiz_assignments
    ADD CONSTRAINT fk22pgnigi0cq6oie8v6ahi6npn FOREIGN KEY (assigned_by) REFERENCES public.users(id);


--
-- Name: student_profiles fk32koy3tgqtaujxhfsn0b9pel2; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_profiles
    ADD CONSTRAINT fk32koy3tgqtaujxhfsn0b9pel2 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: diploma_documents fk4ktqkxk0siqn6igc9obvjgtjk; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.diploma_documents
    ADD CONSTRAINT fk4ktqkxk0siqn6igc9obvjgtjk FOREIGN KEY (id) REFERENCES public.documents(id);


--
-- Name: options fk5bmv46so2y5igt9o9n9w4fh6y; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.options
    ADD CONSTRAINT fk5bmv46so2y5igt9o9n9w4fh6y FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: quiz_attempts fk6t4p4rfdhxkr1o34l42108jci; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT fk6t4p4rfdhxkr1o34l42108jci FOREIGN KEY (reviewed_by) REFERENCES public.users(id);


--
-- Name: passport_documents fk8dbqitkkcbft8nwim94tfxpxr; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.passport_documents
    ADD CONSTRAINT fk8dbqitkkcbft8nwim94tfxpxr FOREIGN KEY (id) REFERENCES public.documents(id);


--
-- Name: student_answers fk8nyksamccim8emu803uhf2da; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_answers
    ADD CONSTRAINT fk8nyksamccim8emu803uhf2da FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: student_answers fk90gegr8390k4wmdu35cer09nx; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_answers
    ADD CONSTRAINT fk90gegr8390k4wmdu35cer09nx FOREIGN KEY (quiz_attempt_id) REFERENCES public.quiz_attempts(id);


--
-- Name: student_quiz_assignments fka3ioj79xtafnk1eeltsc9japu; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_quiz_assignments
    ADD CONSTRAINT fka3ioj79xtafnk1eeltsc9japu FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id);


--
-- Name: chat_messages fkand7mh9iu4kt3n1tn2w9i9of0; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkand7mh9iu4kt3n1tn2w9i9of0 FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: ticket_responses fkb7v24pa6lvgtok2u20sd6et7a; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.ticket_responses
    ADD CONSTRAINT fkb7v24pa6lvgtok2u20sd6et7a FOREIGN KEY (ticket_id) REFERENCES public.tickets(id);


--
-- Name: question_quiz_assignments fkcm1otfbt9x9yaut2d0oi3x47b; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.question_quiz_assignments
    ADD CONSTRAINT fkcm1otfbt9x9yaut2d0oi3x47b FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id);


--
-- Name: users fkd85fw168to2j9jpqdv9j5nlf3; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkd85fw168to2j9jpqdv9j5nlf3 FOREIGN KEY (product_key_id) REFERENCES public.product_keys(id);


--
-- Name: users fke8vhyv59jdia2juxfyci4h4oh; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fke8vhyv59jdia2juxfyci4h4oh FOREIGN KEY (assigned_agent_id) REFERENCES public.users(id);


--
-- Name: quiz_attempts fkfwipvfipnnwsoacoyv5k7fbxc; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT fkfwipvfipnnwsoacoyv5k7fbxc FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id);


--
-- Name: chat_messages fkgiqeap8ays4lf684x7m0r2729; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkgiqeap8ays4lf684x7m0r2729 FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: student_quiz_assignments fkgq9luhsy7x7frbgwoaaufpkfs; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_quiz_assignments
    ADD CONSTRAINT fkgq9luhsy7x7frbgwoaaufpkfs FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: guest_profiles fkgutdrdvn7eri46j18y9lkvra4; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.guest_profiles
    ADD CONSTRAINT fkgutdrdvn7eri46j18y9lkvra4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: ticket_responses fkh1m9hh6ygony3075a7yyyhdn6; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.ticket_responses
    ADD CONSTRAINT fkh1m9hh6ygony3075a7yyyhdn6 FOREIGN KEY (agent_id) REFERENCES public.users(id);


--
-- Name: student_answers fkkjgcncx8ssaj23jtydpwwc0up; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.student_answers
    ADD CONSTRAINT fkkjgcncx8ssaj23jtydpwwc0up FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: quiz_attempts fkl6lkk2u7vw7q7kw3udhupe7ut; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.quiz_attempts
    ADD CONSTRAINT fkl6lkk2u7vw7q7kw3udhupe7ut FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: documents fkl8jfa6b5rwoypt1i3j7i362s1; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkl8jfa6b5rwoypt1i3j7i362s1 FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: progress fklncfduxkce41cgvacrr8x3ex7; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.progress
    ADD CONSTRAINT fklncfduxkce41cgvacrr8x3ex7 FOREIGN KEY (updated_by) REFERENCES public.users(id);


--
-- Name: other_documents fkmddj0rg1bigwqyjn9werttgng; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.other_documents
    ADD CONSTRAINT fkmddj0rg1bigwqyjn9werttgng FOREIGN KEY (id) REFERENCES public.documents(id);


--
-- Name: questions fkmiy2i24hb8838iqkm2kunw286; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkmiy2i24hb8838iqkm2kunw286 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: questions fkn3gvco4b0kewxc0bywf1igfms; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT fkn3gvco4b0kewxc0bywf1igfms FOREIGN KEY (quiz_id) REFERENCES public.quizzes(id);


--
-- Name: agent_profiles fko3kghcnui01ek5p6ymolvgmoc; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.agent_profiles
    ADD CONSTRAINT fko3kghcnui01ek5p6ymolvgmoc FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: cover_letter_documents fko4k63q6eyjea5mg4hf5d7d5g9; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.cover_letter_documents
    ADD CONSTRAINT fko4k63q6eyjea5mg4hf5d7d5g9 FOREIGN KEY (id) REFERENCES public.documents(id);


--
-- Name: question_quiz_assignments fkp4uyifdowxm46cdt727xx4ob3; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.question_quiz_assignments
    ADD CONSTRAINT fkp4uyifdowxm46cdt727xx4ob3 FOREIGN KEY (question_id) REFERENCES public.questions(id);


--
-- Name: cv_documents fkpwttb15b0px22wmyj5qwcw82t; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.cv_documents
    ADD CONSTRAINT fkpwttb15b0px22wmyj5qwcw82t FOREIGN KEY (id) REFERENCES public.documents(id);


--
-- Name: documents fkq17nnmpcqeup72ldkglft9fuo; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkq17nnmpcqeup72ldkglft9fuo FOREIGN KEY (verified_by) REFERENCES public.users(id);


--
-- Name: tickets fkqjo3stj1mn74mupfre7x2yg7k; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fkqjo3stj1mn74mupfre7x2yg7k FOREIGN KEY (agent_id) REFERENCES public.users(id);


--
-- Name: id_card_documents fkqniudrkdxti2hkooa2u20qk6p; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.id_card_documents
    ADD CONSTRAINT fkqniudrkdxti2hkooa2u20qk6p FOREIGN KEY (id) REFERENCES public.documents(id);


--
-- Name: feedback fks0u61qyecspbf8ecaklspmfv0; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fks0u61qyecspbf8ecaklspmfv0 FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: progress fksmkrapfde5wdheuehpg13kk6q; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.progress
    ADD CONSTRAINT fksmkrapfde5wdheuehpg13kk6q FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- Name: feedback fksuloahuvop0q3rpplqsv889iu; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT fksuloahuvop0q3rpplqsv889iu FOREIGN KEY (agent_id) REFERENCES public.users(id);


--
-- Name: tickets fktn7a67w5whlh0wogef5e52elu; Type: FK CONSTRAINT; Schema: public; Owner: linkedu_user
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT fktn7a67w5whlh0wogef5e52elu FOREIGN KEY (student_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict zuYwE4w22bKg9EfYKY5fAJ9P4QualjF1bLPvZnooZChXhKiigPNHnNS5cC774Sd

