package com.linkedu.backend.entities.enums;

public enum ProgressStage {
    ORIENTATION,
    DOSSIER_PREPARATION,
    DOCUMENT_COLLECTION,
    LANGUAGE_TESTS,
    UNIVERSITY_SELECTION,
    APPLICATION_SUBMISSION,
    INTERVIEW_PREPARATION,
    ACCEPTANCE_LETTER,
    VISA_APPLICATION,
    ACCOMMODATION,
    TRAVEL_PLANNING,
    PRE_DEPARTURE,
    ARRIVAL_SETTLEMENT
}