# Generated by Django 6.0.6 on 2026-06-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('missing_skills', models.TextField()),
                ('recommendations', models.TextField()),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cvapp.resume')),
            ],
        ),
    ]
